// surpriseSongs.js
var surpriseSongs = [
  { song: "Detroit Rock City", artist: "Kiss" },
  { song: "Jeremy", artist: "Pearl Jam" },
  { song: "American Pie", artist: "Don McLean" },
  { song: "The Night the Lights Went Out in Georgia", artist: "Vicki Lawrence" },
  { song: "Tears in Heaven", artist: "Eric Clapton" },
  { song: "Hurt", artist: "Johnny Cash" },
  { song: "Mad World", artist: "Gary Jules" },
  { song: "Black", artist: "Pearl Jam" },
  { song: "Alive", artist: "Pearl Jam" },
  { song: "Rooster", artist: "Alice in Chains" },
  { song: "One", artist: "Metallica" },
  { song: "Zombie", artist: "The Cranberries" },
  { song: "Sunday Bloody Sunday", artist: "U2" },
  { song: "The Man in Black", artist: "Johnny Cash" },
  { song: "Fast Car", artist: "Tracy Chapman" },
  { song: "Hallelujah", artist: "Leonard Cohen" },
  { song: "Hurt", artist: "Nine Inch Nails" },
  { song: "Creep", artist: "Radiohead" },
  { song: "Everybody Hurts", artist: "R.E.M." },
  { song: "Losing My Religion", artist: "R.E.M." },
  { song: "Welcome to the Jungle", artist: "Guns N' Roses" },
  { song: "Betterman", artist: "Pearl Jam" },
  { song: "In the Air Tonight", artist: "Phil Collins" },
  { song: "Yesterday", artist: "The Beatles" },
  { song: "Hotel California", artist: "The Eagles" },
  { song: "Bohemian Rhapsody", artist: "Queen" },
  { song: "Stairway to Heaven", artist: "Led Zeppelin" },
  { song: "Imagine", artist: "John Lennon" },
  { song: "Wonderwall", artist: "Oasis" },
  { song: "Sweet Child O' Mine", artist: "Guns N' Roses" },
  { song: "Smells Like Teen Spirit", artist: "Nirvana" },
  { song: "Back in Black", artist: "AC/DC" },
  { song: "Like a Rolling Stone", artist: "Bob Dylan" }
];
